//
//  ScreenAsset.swift
//  DonkeyKong
//
//  Created by Jonathan French on 12.08.24.
//

import Foundation
import SwiftUI

enum AssetType {
    case girder,ladder,blank,oilBL,oilBR,oilTL,oilTR,barBL,barBR,barTL,barTR
}

struct ScreenAsset {
    var assetType:AssetType
    var assetOffset:Double
    
    func assetImage() -> ImageResource {
        switch assetType {
        case .girder:
            ImageResource(name: "Girder", bundle: .main)
        case .ladder:
            ImageResource(name: "Ladder", bundle: .main)
        case .blank:
            ImageResource(name: "Lives", bundle: .main)
        case .oilBL:
            ImageResource(name: "oilBL", bundle: .main)
        case .oilBR:
            ImageResource(name: "oilBR", bundle: .main)
        case .oilTL:
            ImageResource(name: "oilTL", bundle: .main)
        case .oilTR:
            ImageResource(name: "oilTR", bundle: .main)
            
        case .barBL:
            ImageResource(name: "barBL", bundle: .main)
        case .barBR:
            ImageResource(name: "barBR", bundle: .main)
        case .barTL:
            ImageResource(name: "barTL", bundle: .main)
        case .barTR:
            ImageResource(name: "barTR", bundle: .main)

            
        }
    }
    
    init(assetType: AssetType, assetOffset: Double) {
        self.assetType = assetType
        self.assetOffset = assetOffset
    }
    
}

struct Screens {
    
    func getScreenData() -> [[ScreenAsset]] {
        return screen1
    }
    let g = ScreenAsset(assetType: .girder, assetOffset: 0.0)

    let screen1:[[ScreenAsset]] = [
        ///Line1
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line2
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line3
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line4
        [
         ScreenAsset(assetType: .barTL, assetOffset: 4.0),
         ScreenAsset(assetType: .barTR, assetOffset: 4.0),
         ScreenAsset(assetType: .barTL, assetOffset: 4.0),
         ScreenAsset(assetType: .barTR, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line5
        [
         ScreenAsset(assetType: .barBL, assetOffset: 4.0),
         ScreenAsset(assetType: .barBR, assetOffset: 4.0),
         ScreenAsset(assetType: .barBL, assetOffset: 4.0),
         ScreenAsset(assetType: .barBR, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line6
        [
         ScreenAsset(assetType: .barTL, assetOffset: 4.0),
         ScreenAsset(assetType: .barTR, assetOffset: 4.0),
         ScreenAsset(assetType: .barTL, assetOffset: 4.0),
         ScreenAsset(assetType: .barTR, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line7
        [
         ScreenAsset(assetType: .barBL, assetOffset: 4.0),
         ScreenAsset(assetType: .barBR, assetOffset: 4.0),
         ScreenAsset(assetType: .barBL, assetOffset: 4.0),
         ScreenAsset(assetType: .barBR, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line8
        [ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 3.0),
         ScreenAsset(assetType: .girder, assetOffset: 3.0),
         ScreenAsset(assetType: .girder, assetOffset: 2.0),
         ScreenAsset(assetType: .girder, assetOffset: 2.0),
         ScreenAsset(assetType: .girder, assetOffset: 1.0),
         ScreenAsset(assetType: .girder, assetOffset: 1.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line9
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 9.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line10
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 9.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line 11
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 9.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line12
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 1.0),
         ScreenAsset(assetType: .girder, assetOffset: 1.0),
         ScreenAsset(assetType: .girder, assetOffset: 2.0),
         ScreenAsset(assetType: .girder, assetOffset: 2.0),
         ScreenAsset(assetType: .girder, assetOffset: 3.0),
         ScreenAsset(assetType: .girder, assetOffset: 3.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 5.0),
         ScreenAsset(assetType: .girder, assetOffset: 5.0),
         ScreenAsset(assetType: .girder, assetOffset: 5.0),
         ScreenAsset(assetType: .girder, assetOffset: 5.0),
         ScreenAsset(assetType: .girder, assetOffset: 6.0),
         ScreenAsset(assetType: .girder, assetOffset: 6.0),
         ScreenAsset(assetType: .girder, assetOffset: 7.0),
         ScreenAsset(assetType: .girder, assetOffset: 7.0),
         ScreenAsset(assetType: .girder, assetOffset: 8.0),
         ScreenAsset(assetType: .girder, assetOffset: 8.0),
         ScreenAsset(assetType: .girder, assetOffset: 9.0),
         ScreenAsset(assetType: .girder, assetOffset: 9.0),
         ScreenAsset(assetType: .girder, assetOffset: 10.0),
         ScreenAsset(assetType: .girder, assetOffset: 10.0),
         ScreenAsset(assetType: .girder, assetOffset: 11.0),
         ScreenAsset(assetType: .girder, assetOffset: 11.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
         ],
        ///Line13
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 7.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 7.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 8.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line14
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 7.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 7.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line15
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 7.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 7.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 2.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line16
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
          ScreenAsset(assetType: .girder, assetOffset: 11.0),
          ScreenAsset(assetType: .girder, assetOffset: 11.0),
          ScreenAsset(assetType: .girder, assetOffset: 10.0),
          ScreenAsset(assetType: .girder, assetOffset: 10.0),
          ScreenAsset(assetType: .girder, assetOffset: 9.0),
          ScreenAsset(assetType: .girder, assetOffset: 9.0),
          ScreenAsset(assetType: .girder, assetOffset: 8.0),
          ScreenAsset(assetType: .girder, assetOffset: 8.0),
          ScreenAsset(assetType: .girder, assetOffset: 7.0),
          ScreenAsset(assetType: .girder, assetOffset: 7.0),
          ScreenAsset(assetType: .girder, assetOffset: 6.0),
          ScreenAsset(assetType: .girder, assetOffset: 6.0),
          ScreenAsset(assetType: .girder, assetOffset: 6.0),
          ScreenAsset(assetType: .girder, assetOffset: 6.0),
          ScreenAsset(assetType: .girder, assetOffset: 5.0),
          ScreenAsset(assetType: .girder, assetOffset: 5.0),
          ScreenAsset(assetType: .girder, assetOffset: 4.0),
          ScreenAsset(assetType: .girder, assetOffset: 4.0),
          ScreenAsset(assetType: .girder, assetOffset: 3.0),
          ScreenAsset(assetType: .girder, assetOffset: 3.0),
          ScreenAsset(assetType: .girder, assetOffset: 2.0),
          ScreenAsset(assetType: .girder, assetOffset: 2.0),
          ScreenAsset(assetType: .girder, assetOffset: 1.0),
          ScreenAsset(assetType: .girder, assetOffset: 1.0),
          ScreenAsset(assetType: .girder, assetOffset: 0.0),
          ScreenAsset(assetType: .girder, assetOffset: 0.0),
          ScreenAsset(assetType: .blank, assetOffset: 0.0),
          ScreenAsset(assetType: .blank, assetOffset: 0.0),
          ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line17
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 7.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 1.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line18
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 1.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line19
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 3.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 2.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line20
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
          ScreenAsset(assetType: .blank, assetOffset: 0.0),
          ScreenAsset(assetType: .blank, assetOffset: 0.0),
          ScreenAsset(assetType: .girder, assetOffset: 0.0),
          ScreenAsset(assetType: .girder, assetOffset: 0.0),
          ScreenAsset(assetType: .girder, assetOffset: 1.0),//ladder top
          ScreenAsset(assetType: .girder, assetOffset: 1.0),
          ScreenAsset(assetType: .girder, assetOffset: 2.0),
          ScreenAsset(assetType: .girder, assetOffset: 2.0),
          ScreenAsset(assetType: .girder, assetOffset: 3.0),
          ScreenAsset(assetType: .girder, assetOffset: 3.0),
          ScreenAsset(assetType: .girder, assetOffset: 4.0),
          ScreenAsset(assetType: .girder, assetOffset: 4.0),
          ScreenAsset(assetType: .girder, assetOffset: 5.0),
          ScreenAsset(assetType: .girder, assetOffset: 5.0),// ladder top
          ScreenAsset(assetType: .girder, assetOffset: 6.0),
          ScreenAsset(assetType: .girder, assetOffset: 6.0),
          ScreenAsset(assetType: .girder, assetOffset: 7.0),
          ScreenAsset(assetType: .girder, assetOffset: 7.0),
          ScreenAsset(assetType: .girder, assetOffset: 8.0),
          ScreenAsset(assetType: .girder, assetOffset: 8.0),
          ScreenAsset(assetType: .girder, assetOffset: 9.0),
          ScreenAsset(assetType: .girder, assetOffset: 9.0),
          ScreenAsset(assetType: .girder, assetOffset: 10.0),
          ScreenAsset(assetType: .girder, assetOffset: 10.0),
          ScreenAsset(assetType: .girder, assetOffset: 11.0),
          ScreenAsset(assetType: .girder, assetOffset: 11.0),
          ScreenAsset(assetType: .girder, assetOffset: 12.0),
          ScreenAsset(assetType: .girder, assetOffset: 12.0),
          ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line21
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 2.0),//here
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),//here
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line22
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 2.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),//h
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line23
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 7.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 4.0),//h
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line24
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 10.0),
         ScreenAsset(assetType: .girder, assetOffset: 10.0),
         ScreenAsset(assetType: .girder, assetOffset: 9.0),
         ScreenAsset(assetType: .girder, assetOffset: 9.0),
         ScreenAsset(assetType: .girder, assetOffset: 8.0),/// ladder bot
         ScreenAsset(assetType: .girder, assetOffset: 8.0),
         ScreenAsset(assetType: .girder, assetOffset: 7.0),
         ScreenAsset(assetType: .girder, assetOffset: 7.0),
         ScreenAsset(assetType: .girder, assetOffset: 7.0),
         ScreenAsset(assetType: .girder, assetOffset: 7.0),
         ScreenAsset(assetType: .girder, assetOffset: 6.0),
         ScreenAsset(assetType: .girder, assetOffset: 6.0),
         ScreenAsset(assetType: .girder, assetOffset: 5.0),
         ScreenAsset(assetType: .girder, assetOffset: 5.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),///Ladder bot
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 3.0),
         ScreenAsset(assetType: .girder, assetOffset: 3.0),
         ScreenAsset(assetType: .girder, assetOffset: 2.0),
         ScreenAsset(assetType: .girder, assetOffset: 2.0),
         ScreenAsset(assetType: .girder, assetOffset: 1.0),
         ScreenAsset(assetType: .girder, assetOffset: 1.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
         ],
        ///Line25
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 6.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 2.3),//h
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line26
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .oilTL, assetOffset: 1.0),
         ScreenAsset(assetType: .oilTR, assetOffset: 1.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 2.3),//h
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line27
        [ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .oilBL, assetOffset: 1.0),
         ScreenAsset(assetType: .oilBR, assetOffset: 1.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .ladder, assetOffset: 2.3),//h
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0),
         ScreenAsset(assetType: .blank, assetOffset: 0.0)
        ],
        ///Line28
        [ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 0.0),
         ScreenAsset(assetType: .girder, assetOffset: 1.0),
         ScreenAsset(assetType: .girder, assetOffset: 1.0),
         ScreenAsset(assetType: .girder, assetOffset: 2.0),
         ScreenAsset(assetType: .girder, assetOffset: 2.0),
         ScreenAsset(assetType: .girder, assetOffset: 3.0),
         ScreenAsset(assetType: .girder, assetOffset: 3.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 4.0),
         ScreenAsset(assetType: .girder, assetOffset: 5.0),
         ScreenAsset(assetType: .girder, assetOffset: 5.0),
         ScreenAsset(assetType: .girder, assetOffset: 6.0),
         ScreenAsset(assetType: .girder, assetOffset: 6.0),
         ScreenAsset(assetType: .girder, assetOffset: 7.0)
        ]

    ]
    
}
